[package]
name = "tuinix"
version = "0.1.0"
edition = "2024"

[dependencies]
libc = "0.2.172"
mio = { version = "1.0.3", default-features = false, features = ["os-poll", "os-ext"] }
unicode-width = "0.2.0"
